// Code generated by MockGen. DO NOT EDIT.
// Source: app/domain/balance/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=app/domain/balance/interfaces.go -destination=app/domain/balance/mock.go -package=domainbalance
//

// Package domainbalance is a generated GoMock package.
package domainbalance

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDomainItf is a mock of DomainItf interface.
type MockDomainItf struct {
	ctrl     *gomock.Controller
	recorder *MockDomainItfMockRecorder
}

// MockDomainItfMockRecorder is the mock recorder for MockDomainItf.
type MockDomainItfMockRecorder struct {
	mock *MockDomainItf
}

// NewMockDomainItf creates a new mock instance.
func NewMockDomainItf(ctrl *gomock.Controller) *MockDomainItf {
	mock := &MockDomainItf{ctrl: ctrl}
	mock.recorder = &MockDomainItfMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainItf) EXPECT() *MockDomainItfMockRecorder {
	return m.recorder
}

// DisburmentBalance mocks base method.
func (m *MockDomainItf) DisburmentBalance(ctx context.Context, req DisburmentBalanceRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DisburmentBalance", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// DisburmentBalance indicates an expected call of DisburmentBalance.
func (mr *MockDomainItfMockRecorder) DisburmentBalance(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DisburmentBalance", reflect.TypeOf((*MockDomainItf)(nil).DisburmentBalance), ctx, req)
}

// GetBalanceByUserId mocks base method.
func (m *MockDomainItf) GetBalanceByUserId(ctx context.Context, userId string) (Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceByUserId", ctx, userId)
	ret0, _ := ret[0].(Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceByUserId indicates an expected call of GetBalanceByUserId.
func (mr *MockDomainItfMockRecorder) GetBalanceByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceByUserId", reflect.TypeOf((*MockDomainItf)(nil).GetBalanceByUserId), ctx, userId)
}

// GetHistorySummaryByUserIdAndType mocks base method.
func (m *MockDomainItf) GetHistorySummaryByUserIdAndType(ctx context.Context, userId string, historyType int) ([]HistorySummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistorySummaryByUserIdAndType", ctx, userId, historyType)
	ret0, _ := ret[0].([]HistorySummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistorySummaryByUserIdAndType indicates an expected call of GetHistorySummaryByUserIdAndType.
func (mr *MockDomainItfMockRecorder) GetHistorySummaryByUserIdAndType(ctx, userId, historyType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistorySummaryByUserIdAndType", reflect.TypeOf((*MockDomainItf)(nil).GetHistorySummaryByUserIdAndType), ctx, userId, historyType)
}

// GetLatestHistoryByUserId mocks base method.
func (m *MockDomainItf) GetLatestHistoryByUserId(ctx context.Context, userId string) ([]History, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestHistoryByUserId", ctx, userId)
	ret0, _ := ret[0].([]History)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestHistoryByUserId indicates an expected call of GetLatestHistoryByUserId.
func (mr *MockDomainItfMockRecorder) GetLatestHistoryByUserId(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestHistoryByUserId", reflect.TypeOf((*MockDomainItf)(nil).GetLatestHistoryByUserId), ctx, userId)
}

// GrantBalanceByUserId mocks base method.
func (m *MockDomainItf) GrantBalanceByUserId(ctx context.Context, balance Balance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantBalanceByUserId", ctx, balance)
	ret0, _ := ret[0].(error)
	return ret0
}

// GrantBalanceByUserId indicates an expected call of GrantBalanceByUserId.
func (mr *MockDomainItfMockRecorder) GrantBalanceByUserId(ctx, balance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantBalanceByUserId", reflect.TypeOf((*MockDomainItf)(nil).GrantBalanceByUserId), ctx, balance)
}
